name: Build and push image to GHCR

on:
  push:
    branches:
      - 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: glob
          tags: latest
          platforms: linux/amd64, linux/386, linux/arm64, linux/arm/v7, linux/arm/v6
          containerfiles: |
              ./Dockerfile
      -
        name: Push To GHCR
        id: push_to_ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Push To Dockerhub
        id: push_to_dockerhub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ secrets.DOCKERHUB_USERNAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        

